### PR TITLE
SHTC1 parameter update

### PR DESCRIPTION
**Pull request by hmueller01**
fix SHTC1 sensor parameter (see datasheet)

### CODE REVIEW

**Comment by winkj** [comment]
Thanks for the submission. In this case, the code is correct over the datasheet (see explanation below). SHT3x and SHT4x datasheets already reflect this, and list "(2^16) -1" as divisor.

**Explanation:** the data read from the bus is 16 bits, and therefore can't be larger than 65535 (0xFFFF). While the error of using 65536 (0x10000) as a divisor is miniscule, it would still prevent the sensor from ever reaching the max value, and would also not fit in a 16-bit value.

**Comment by hmueller01** [comment]
Yes, values bigger than 65535 can't be received. But I think this is not the point. Values less than 3.146 lead to negative RH and should not be transmitted by SHT21 eighter. So this is just a formula how the received values shall be calculated to physical values. I wonder that Sensirion never changed this in their datasheet (they did updates/corrections) if this is really wrong. At the end of the day the difference is at the second digit after the dot and below the resolution of the sensor. My intention was just to be conform with the datasheet ...

**Comment by winkj** [comment]
> So this is just a formula how the received values shall be calculated to physical values

Let's do this with the example of the SHTC1 relative humidity formula:

`RH = 100 * (S_RH / x)`

S_RH is a 16-bit value, i.e. it will max out at 0xFFFF/65535. When using `x = 65535` as we do in our driver, RH can go to 100%. If we use `x = 65536` as in the datasheet, we can at most get to 99.9984741211%. Of course, the inaccuracy introduced by the latter is way lower than the accuracy of the sensor itself, and as mentioned above, miniscule; however mathematically speaking, it does not allow to cover the specified RH range of the sensor (0..100% RH).

Since we're doing float divisions anyway, we decided to use the mathematically correct value in this driver. (Sidenote: If you want to stay in the fixed-point world, staying with a power of two will make things easier, which we're making use of for example in https://github.com/Sensirion/embedded-sht)

**Comment by hmueller01** [comment]
Sorry, but no. The SHT21 formula for RH is
RH = -6 + 125 * (S_RH / 2^16)
So, if we ever get S_RH = 65535 we will get 118,998 %RH (or 119 %RH if we use 2^16-1) which is invalid (as RH can not go above 100 %RH). So it really does not matter and the only thing is using the value written in the datasheet or not. 

But thanks for the discussion. Before that I wasn't aware how big the difference really is. We can really forget about that.

**Pull request closed without merging**
